version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: procureerp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
 
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
 
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev

volumes:
  postgres-data: {} # または単に postgres-data: で改行